### ISSUE TITLE
NULL PyObject when Calling Baseline

### ISSUE THREAD

**Issue by besselfunct** [charlesll/Spectra.jl#17]
I've been trying to get this library to work on my installation, and I feel like I'm really close, but I'm running into an issue.

I've made sure all of my inputs are of the proper type, and I try to run the basic example command:
```
Y_corr, Y_baseline = baseline(wavelength, data[2,:], roi, "poly", polynomial_order=2)
```
and I get the following output:
```
ERROR: ArgumentError: ref of NULL PyObject
Stacktrace:
 [1] _getproperty at C:\Users\*user*\.julia\packages\PyCall\tqyST\src\PyCall.jl:299 [inlined]
 [2] __getproperty(::PyCall.PyObject, ::Symbol) at C:\Users\*user*\.julia\packages\PyCall\tqyST\src\PyCall.jl:306
 [3] getproperty at C:\Users\*user*\.julia\packages\PyCall\tqyST\src\PyCall.jl:312 [inlined]
 [4] baseline(::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,2}, ::String; polynomial_order::Int64, s::Float64, lam::Int64, p::Float64, ratio::Float64, niter::Int64, p0_exp::Array{Float64,1}, p0_log::Array{Float64,1}) at C:\Users\*user*\.julia\packages\Spectra\HGaGF\src\baseline.jl:86
 [5] top-level scope at none:1
```
(with my name redacted from the directories)

I've verified that my rampy install is "working" as I can import it in the python3 powershell environment.

**Comment by kkakosim** [comment]
without implying that I understand the source of error, when I had the same error (with specific datasets) I needed to convert my arrays
```
wvlth_array=convert(Array{Float64}, wavelength)
data_array=convert(Array{Float64}, data[2,:])
Y_corr, Y_baseline = baseline(wvlth_array, data_array, roi, "poly", polynomial_order=2)
```

**Comment by besselfunct** [comment]
So, I went to bed last night, and tried to re-execute my code this morning, and I'm no longer able to execute the ```using Spectra``` command without errors, so I think something is borked with my rampy installation. I had to rerun conda install rampy in order to get Spectra to import properly.

I did verify that all of my types were correct by running typeof(*var*) before I filed the issue. I had to correct my ROI array as it was defaulting to Int64 instead of Float64.

Just for thoroughness though, I reproduced the error, and checked my types:
```
julia> typeof(wav)
Array{Float64,1}
julia> typeof(testdat)
Array{Float64,1}
julia> typeof(roi)
Array{Float64,2}
```

I'm sure it's possible that my Anaconda install is improperly configured, but I'm not sure how I would fix it.

**Comment by besselfunct** [comment]
Looking further into what might be the issue, I tried to import rampy from PyCall directly.
```
julia> Pycall.conda
true
julia> Pycall.current_python()
"C:\\Users\\*user*\\.julia\\conda\\3\\python.exe"
julia> rp = pyimport("rampy")
ERROR: PyError (PyImport_ImportModule

The Python package rampy could not be imported by pyimport. Usually this means
that you did not install rampy in the Python version being used by PyCall.

PyCall is currently configured to use the Julia-specific Python distribution
installed by the Conda.jl package.  To install the rampy module, you can
use `pyimport_conda("rampy", PKG)`, where PKG is the Anaconda
package the contains the module rampy, or alternatively you can use the
Conda package directly (via `using Conda` followed by `Conda.add` etcetera).

Alternatively, if you want to use a different Python distribution on your
system, such as a system-wide Python (as opposed to the Julia-specific Python),
you can re-configure PyCall with that Python.   As explained in the PyCall
documentation, set ENV["PYTHON"] to the path/name of the python executable
you want to use, run Pkg.build("PyCall"), and re-launch Julia.

) <class 'ModuleNotFoundError'>
ModuleNotFoundError("No module named 'rampy'")

Stacktrace:
 [1] pyimport(::String) at C:\Users\*user*\.julia\packages\PyCall\tqyST\src\PyCall.jl:547
 [2] top-level scope at none:1
```
Attempts to install rampy via Conda.jl are unsuccessful, as there's apparently not a windows conda package for rampy.

I tried navigating to the Julia python install, and installing rampy via pip
```
C:\Users\*user*\.julia\conda\3> ./python.exe -m pip install rampy
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/rampy/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/rampy/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/rampy/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/rampy/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/rampy/
Could not fetch URL https://pypi.org/simple/rampy/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/rampy/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement rampy (from versions: none)
ERROR: No matching distribution found for rampy
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
```
which was obviously unsuccessful. 

It seems like it definitely has something to do with the current python version that Spectra is trying to call, but I'm unsure of how to resolve this. I'm hesitant to start adding things to my PATH, as that feels like a quick and easy way to break a lot of stuff.

**Comment by besselfunct** [comment]
Sorry for dumping so much stuff here.

Just for the sake of trying, I moved to a fresh install of Windows 10, installed Julia, and tried to ```pkg] add Spectra``` with the same results as listed before.

I've also got a fresh install of Pop!_OS 20.04 LTS in the lab, so I tried installing Julia and Spectra there. ```pkg] add Spectra``` was unable to fully install the package, so I had to manually install pip3 on the primary system python install, and then ```pip3 install rampy```

However, when I tried the same call to baseline
```Y_corr, Y_base = baseline(wavelength, intensity, roi, "poly", polynomial_order = 2)```
it throws the same errors as before.
```
ERROR: ArgumentError: ref of NULL PyObject
Stacktrace:
 [1] _getproperty at /root/.julia/packages/PyCall/tqyST/src/PyCall.jl:299 [inlined]
 [2] __getproperty(::PyCall.PyObject, ::Symbol) at /root/.julia/packages/PyCall/tqyST/src/PyCall.jl:306
 [3] getproperty at /root/.julia/packages/PyCall/tqyST/src/PyCall.jl:312 [inlined]
 [4] baseline(::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,2}, ::String; polynomial_order::Int64, s::Float64, lam::Int64, p::Float64, ratio::Float64, niter::Int64, p0_exp::Array{Float64,1}, p0_log::Array{Float64,1}) at /root/.julia/packages/Spectra/HGaGF/src/baseline.jl:86
 [5] top-level scope at REPL[34]:1
```

**Comment by kkakosim** [comment]
do you get any error while running `using Spectra` ?
installing rampy on your python install will not help unless Julia uses that python. I think by default it uses the python installed with Julia/PyCall.

the most recent successful installation of Spectra was with the following sequence:
```
]add Spectra
]add PyCall
using PyCall
@pyimport pip
pip.main(["install", "rampy"])
```

**Comment by besselfunct** [comment]
I usually do get errors when trying to execute ```using Spectra``` at least the first time the Julia environment is initialized. It was fixed (strangely) by running ```pip install rampy``` in one of my conda environments, which Julia was not referencing.

The code snippet you sent was successful at installing the ```rampy``` package though, and I've been able to execute the baseline function correctly.

Is there something that needs to be changed in the package script in order to make the code snippet you've given work? Should it be incorporated into the installation instructions section of the Readme? I'm not sure I would have arrived at that code without assistance.

**Comment by kkakosim** [comment]
Indeed, it would help adding these steps in installation. Depending of the starting point e.g. a standalone Python outside Julia with the appropriate configuration.

> I usually do get errors when trying to execute using Spectra at least the first time the Julia environment is initialized. It was fixed (strangely) by running pip install rampy in one of my conda environments, which Julia was not referencing.

You need to check which Python you are using in the Julia
>To force Julia to use its own Python distribution, via Conda, simply set ENV["PYTHON"] to the empty string "" and re-run Pkg.build("PyCall").
https://github.com/JuliaPy/PyCall.jl

**Comment by charlesll** [comment]
Hi, those errors probably result from a problem with PyCall... The necessary thing is to install PyCall first, then set the environment as @kkakosim indicated above: set ENV["PYTHON"] to the empty string "" 

Then, install  Spectra directly. The installer actually launch the function pip.main(["install", "rampy"]).

**Comment by besselfunct** [comment]
I can verify that the issue was with PyCall, however as a new Julia user, the error was particularly frustrating trying to track down. I'm assuming the reason you don't set the PyCall environment variable during install is to avoid borking any other dependent libraries. Is there a more elegant solution to this problem than just including additional steps in the install instructions?

**Comment by besselfunct** [comment]
Added verbiage to the Installation instructions to indicate the correct installation procedure for a Vanilla install.

**Comment by charlesll** [comment]
> I can verify that the issue was with PyCall, however as a new Julia user, the error was particularly frustrating trying to track down. I'm assuming the reason you don't set the PyCall environment variable during install is to avoid borking any other dependent libraries. Is there a more elegant solution to this problem than just including additional steps in the install instructions?

Just for clarifying things here : we do not want to modify the PyCall install because this relates to PyCall, not Spectra. This will be the last thing to do because PyCall is called by many other libraries, so it's out of question to fiddle during Spectra installation (or any other package) with the PyCall install.

Thanks for the mods in the ReadMe !
