### ISSUE TITLE
Julia 1.0.1: Error building Spectra

### ISSUE THREAD

**Issue by AndiMD** [charlesll/Spectra.jl#7]
Hi,

What is the state of Julia 1.0 compatibility? Currently, I get this error:

```
 Building Spectra → `~/.julia/packages/Spectra/Lseeg/deps/build.log`
┌ Error: Error building `Spectra`: 
│ ERROR: LoadError: syntax: unsupported `const` declaration on local variable around /home/andi/.julia/packages/PyCall/0jMpb/src/PyCall.jl:536
│ Stacktrace:
│  [1] include at ./boot.jl:317 [inlined]
│  [2] include_relative(::Module, ::String) at ./loading.jl:1041
│  [3] include(::Module, ::String) at ./sysimg.jl:29
│  [4] include(::String) at ./client.jl:388
│  [5] top-level scope at none:0
│ in expression starting at /home/andi/.julia/packages/Spectra/Lseeg/deps/build.jl:16
│ Running build.jl for the Spectra package.
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1069
```

Using Julia 1.0.1 Linux 64bit with:
PyCall v1.18.5, NMF v0.4.0, Spectra v0.3.6+ #master

Thanks.
Andreas

**Comment by charlesll** [comment]
Hi,

Currently I'm having problems building on 0.7/1.0, but it is related to install of gcvspline through PyPI which can fail with the new 0.7/1.0 Julia...

I never saw your error; I will try replicating it.

**Comment by charlesll** [comment]
Everything has been updated to work with 1.0 or higher in the new Spectra 0.4 release.

Breaking change are introduced, so please have a look at the documentation before use, and modify your code accordingly!

Cheers, C.
