### ISSUE TITLE
pycall api updates

### ISSUE THREAD

**Issue by stevengj** [charlesll/Spectra.jl#9]
PyCall 1.90.0 is now released, which change `o[:foo]` and `o["foo"]` to `o.foo` and `o."foo"`, respectively, for python objects `o`; see also JuliaPy/PyCall.jl#629.

The old `getindex` methods still work but are deprecated, so you'll want to put out a new release that uses the new methods and REQUIREs PyCall 1.90.0 to avoid having zillions of deprecation messages.

**Comment by charlesll** [comment]
Ok thanks for the warning. I will update Spectra accordingly!

**Comment by charlesll** [comment]
@stevengj tried to switch from o[:foo] to o.foo in my functions.

I must be doing something wrong but I get the traditional 'LoadError: type PyObject has no field foo'??

(see for instance src/baseline.jl)

**Comment by charlesll** [comment]
but calling rampy.baseline in a notebook works, so I don't understand what is wrong there?

**Comment by stevengj** [comment]
Probably the version of PyCall you are using is too old?

**Comment by charlesll** [comment]
1.91... so this should be OK?

**Comment by stevengj** [comment]
Yes, PyCall 1.91 in Julia 0.7 or later should be okay.  Are you accidentally running in an older Julia version?  Or maybe you are running in a Pkg environment where PyCall is pinned to an older version?

**Comment by charlesll** [comment]
No... I'm running in Julia 1.1.0... And PyCall was 1.91... I will triple check with a brand new installation I think.

**Comment by charlesll** [comment]
Problem solved, everything working. Release of v0.4.1.

@JuliaRegistrator register()
